<a href="https://colab.research.google.com/github/faiyaz0987/Deel/blob/main/6C_Max_pooling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from tensorflow.keras.layers import MaxPooling2D

In [8]:
random_matrix_3 = np.random.randint(-10, 11, size=(3, 3)).astype(float)
print(random_matrix_3)
max_1 = MaxPooling2D(pool_size=(2, 2), strides=(1,1))
# Reshape the input to be 4-dimensional (batch_size, height, width, channels)
input_matrix = random_matrix_3.reshape(1, 3, 3, 1)
print(input_matrix)
# Apply max pooling to the input matrix
output_matrix = max_1(input_matrix)
print(output_matrix)

[[-3.  6.  2.]
 [ 3.  1.  1.]
 [ 3.  9.  9.]]
[[[[-3.]
   [ 6.]
   [ 2.]]

  [[ 3.]
   [ 1.]
   [ 1.]]

  [[ 3.]
   [ 9.]
   [ 9.]]]]
tf.Tensor(
[[[[6.]
   [6.]]

  [[9.]
   [9.]]]], shape=(1, 2, 2, 1), dtype=float32)


In [9]:
random_matrix_4 = np.random.randint(-10, 11, size=(4, 4)).astype(float)
print(random_matrix_4)

[[-7. -3.  9.  2.]
 [-1.  8.  9. -7.]
 [-9.  7. -8.  1.]
 [-9.  6. -8. -4.]]


In [10]:
input_matrix = random_matrix_4.reshape(1, 4, 4, 1)
print(input_matrix)

[[[[-7.]
   [-3.]
   [ 9.]
   [ 2.]]

  [[-1.]
   [ 8.]
   [ 9.]
   [-7.]]

  [[-9.]
   [ 7.]
   [-8.]
   [ 1.]]

  [[-9.]
   [ 6.]
   [-8.]
   [-4.]]]]


In [18]:
max_pool_2 = MaxPooling2D(pool_size=(2, 2), strides=(1,1), padding = 'valid')
print(max_pool_2(input_matrix))

tf.Tensor(
[[[[8.]
   [9.]
   [9.]]

  [[8.]
   [9.]
   [9.]]

  [[7.]
   [7.]
   [1.]]]], shape=(1, 3, 3, 1), dtype=float32)
