<a href="https://colab.research.google.com/github/faiyaz0987/Deel/blob/main/LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, Dropout
from tensorflow.keras.datasets import imdb
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l1

In [19]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=20000)

In [20]:
X_train = sequence.pad_sequences(X_train, maxlen=80)
X_test = sequence.pad_sequences(X_test, maxlen=80)


In [21]:
model = Sequential()
model.add(Embedding(20000,128))
model.add(LSTM(128, activation = "tanh", recurrent_activation="sigmoid", dropout=0.1, recurrent_dropout=0.1, kernel_regularizer=l1(0.01)))
model.add(Dense(1, activation="sigmoid"))
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
learning_rate = 0.0001
optimizer = Adam(learning_rate)
model.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

In [23]:
lstm = model.fit(X_train, y_train, batch_size=32, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 236s 297ms/step - accuracy: 0.5931 - loss: 21.9763 - val_accuracy: 0.7405 - val_loss: 2.0987
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 233s 298ms/step - accuracy: 0.7823 - loss: 1.1061 - val_accuracy: 0.7764 - val_loss: 0.5915
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 235s 301ms/step - accuracy: 0.8267 - loss: 0.5330 - val_accuracy: 0.7480 - val_loss: 0.5837
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 239s 306ms/step - accuracy: 0.8512 - loss: 0.4622 - val_accuracy: 0.7828 - val_loss: 0.5260
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 231s 296ms/step - accuracy: 0.8750 - loss: 0.4048 - val_accuracy: 0.7851 - val_loss: 0.5108


In [24]:
predictions = model.predict(X_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 38s 48ms/step


In [25]:
predictions

array([[0.10796049],
       [0.9157499 ],
       [0.8068843 ],
       ...,
       [0.08905394],
       [0.19216822],
       [0.76158714]], dtype=float32)

In [26]:
display(predictions)

array([[0.10796049],
       [0.9157499 ],
       [0.8068843 ],
       ...,
       [0.08905394],
       [0.19216822],
       [0.76158714]], dtype=float32)

In [29]:
import numpy as np
from sklearn.metrics import accuracy_score

# Convert predictions to binary labels (0 or 1)
predicted_labels = (predictions > 0.5).astype(int)

# Calculate accuracy
accuracy = accuracy_score(y_test, predicted_labels)

print(f"Model Accuracy: {accuracy}")
print(predicted_labels)

Model Accuracy: 0.78508
[[0]
 [1]
 [1]
 ...
 [0]
 [0]
 [1]]


In [30]:
display("Predicted Labels:", predicted_labels[:10])
display("True Labels:", y_test[:10])

'Predicted Labels:'

array([[0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1]])

'True Labels:'

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1])